services:
  postgres:
    image: postgres:16
    container_name: ai_incident_commander_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: incident_admin
      POSTGRES_DB: ai_incident_commander

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: