import React, { useState } from 'react';
import { EyeIcon, EyeOffIcon, LockKeyholeIcon, TerminalIcon } from 'lucide-react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';

export function Login() {
  const { isAuthenticated, login } = useAuth(); const { theme, toggleTheme } = useTheme();
  const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState('admin@example.com'); const [password, setPassword] = useState('admin123'); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  if (isAuthenticated) return <Navigate to="/" replace />;
  const submit = async (e) => { e.preventDefault(); setError(''); setLoading(true); try { await login(email, password); navigate(location.state?.from?.pathname || '/', { replace: true }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <main className="flex min-h-screen items-center justify-center bg-canvas p-5 text-fg"><button onClick={toggleTheme} className="absolute right-5 top-5 rounded-md border border-line bg-panel px-3 py-2 text-xs text-fg2">{theme === 'dark' ? 'Light mode' : 'Dark mode'}</button><section className="w-full max-w-md rounded-xl border border-line bg-panel p-7 shadow-2xl sm:p-9"><div className="mb-8"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-ai/15 text-ai ring-1 ring-ai/30"><TerminalIcon className="h-5 w-5" /></span><h1 className="mt-5 text-xl font-semibold">AI Incident Commander</h1><p className="mt-2 text-sm text-fg3">Sign in to your incident response workspace.</p></div><form onSubmit={submit} className="space-y-4"><label className="block text-xs font-medium text-fg2">Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" className="mt-1.5 h-10 w-full rounded-md border border-line bg-canvas px-3 text-sm text-fg outline-none focus:border-ai" required /></label><label className="block text-xs font-medium text-fg2">Password<span className="relative mt-1.5 block"><input value={password} onChange={(e) => setPassword(e.target.value)} type={show ? 'text' : 'password'} className="h-10 w-full rounded-md border border-line bg-canvas px-3 pr-10 text-sm text-fg outline-none focus:border-ai" required /><button type="button" onClick={() => setShow(!show)} className="absolute right-2 top-2 text-fg3" aria-label="Toggle password visibility">{show ? <EyeOffIcon className="h-4 w-4" /> : <EyeIcon className="h-4 w-4" />}</button></span></label><div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2 text-fg2"><input type="checkbox" defaultChecked className="accent-indigo-500" />Remember me</label><button type="button" className="text-ai hover:underline">Forgot password?</button></div>{error && <p className="rounded-md bg-crit/10 px-3 py-2 text-xs text-crit">{error}</p>}<button disabled={loading} className="flex h-10 w-full items-center justify-center gap-2 rounded-md bg-ai text-sm font-semibold text-white hover:bg-ai/90 disabled:opacity-60"><LockKeyholeIcon className="h-4 w-4" />{loading ? 'Signing in…' : 'Sign In'}</button></form><p className="mt-6 text-center text-2xs text-fg3">Demo: admin@example.com · admin123</p></section></main>;
}
